version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf ./manual/book

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets
      - cmd: cargo +stable clean

  cov:
    desc: Generates code coverage report in text format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates code coverage report in HTML format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --html --open

  cov-badge:
    desc: Generates the detailed code coverage badge
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --json --summary-only | coverio -l coverage -c --tag cov-badge-normalized-line-endings

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc

  doc-private:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --document-private-items

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --open

  doc-private-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --open --document-private-items

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +stable fmt

  manual:
    desc: Builds the manual from its markdown files
    cmds:
      - cmd: cd manual && mdbook build

  readme:
    desc: Regenerates README.md file from its parts
    cmds:
      - cmd: cat readme/README_HEADER.md readme/README_BODY.md readme/README_FOOTER.md > README.md
      - cmd: cp readme/README_BODY.md manual/src/readme.md

  serve:
    desc: Serves the manual locally and rebuilds on changes
    silent: true
    ignore_error: true
    cmds:
      - cmd: cd manual && mdbook serve || true

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run
